/* original data sources: 

http://www.pwrc.usgs.gov/bbl/manual/speclist.cfm 
AND 
http://www.pwrc.usgs.gov/bbl/MANUAL/gallaou.htm
AND
http://www.rmbo.org/public/monitoring/protocols/Field_protocol_for_spacially_balanced_sampling_2010_V3.pdf (unidentified codes)
*/

birdBrain	= {

	ABDU: { name: "American Black Duck" },
	ABDX: { name: "American Black Duck Dominant x Mallard Hybrid" },
	ABTO: { name: "Abert's Towhee" },
	ACFL: { name: "Acadian Flycatcher" },
	ACGO: { name: "Aleutian Canada Goose" },
	ACHU: { name: "Antillean Crested Hummingbird" },
	ACWO: { name: "Acorn Woodpecker" },
	ADPE: { name: "Adélie Penguin" },
	ADWA: { name: "Adelaide's Warbler" },
	AFCD: { name: "African Collared-Dove" },
	AFOW: { name: "Ashy-faced Owl" },
	AFPE: { name: "African Penguin" },
	AFSI: { name: "African Silverbill" },
	AGWT: { name: "American Green-winged Teal" },
	AKEK: { name: "ʻAkekeʻe" },
	AKEP: { name: "ʻAkepa" },
	AKIK: { name: "ʻAkikiki" },
	AKIP: { name: "ʻAkiapōlāʻau" },
	AKOH: { name: "ʻAkohekohe" },
	ALFL: { name: "Alder Flycatcher" },
	ALHU: { name: "Allen's Hummingbird" },
	ALOR: { name: "Altamira Oriole" },
	ALTE: { name: "Aleutian Tern" },
	AMAV: { name: "American Avocet" },
	AMBI: { name: "American Bittern" },
	AMCO: { name: "American Coot" },
	AMCR: { name: "American Crow" },
	AMDI: { name: "American Dipper" },
	AMFL: { name: "American Flamingo" },
	AMGO: { name: "American Goldfinch" },
	AMGP: { name: "American Golden-Plover" },
	AMKE: { name: "American Kestrel" },
	AMOY: { name: "American Oystercatcher" },
	AMPI: { name: "American Pipit" },
	AMRE: { name: "American Redstart" },
	AMRO: { name: "American Robin" },
	AMWI: { name: "American Wigeon" },
	AMWO: { name: "American Woodcock" },
	ANEU: { name: "Antillean Euphonia" },
	ANHI: { name: "Anhinga" },
	ANHU: { name: "Anna's Hummingbird" },
	ANIA: { name: "ʻAnianiau" },
	ANMA: { name: "Antillean Mango" },
	ANMU: { name: "Ancient Murrelet" },
	ANNI: { name: "Antillean Nighthawk" },
	ANPE: { name: "Antarctic Petrel" },
	ANTE: { name: "Antarctic Tern" },
	APAP: { name: "ʻApapane" },
	APFA: { name: "Aplomado Falcon" },
	ARLO: { name: "Arctic Loon" },
	ARRW: { name: "Arrowhead Warbler" },
	ARTE: { name: "Arctic Tern" },
	ARWA: { name: "Arctic Warbler" },
	ASSP: { name: "Ashy Storm-Petrel" },
	ATBR: { name: "Atlantic Brant" },
	ATFL: { name: "Ash-throated Flycatcher" },
	ATPU: { name: "Atlantic Puffin" },
	ATSP: { name: "American Tree Sparrow" },
	ATTW: { name: "American Three-toed Woodpecker" },
	AUOR: { name: "Audubon's Oriole" },
	AUSH: { name: "Audubon's Shearwater" },
	AUWA: { name: "Audubon's Warbler" },
	AWPE: { name: "American White Pelican" },
	AZTH: { name: "Aztec Thrush" },
	BABI: { name: "Black x Atlantic Brant Intergrade" },
	BACG: { name: "Baja Gnatcatcher" },
	BACS: { name: "Bachman's Sparrow" },
	BAEA: { name: "Bald Eagle" },
	BAGO: { name: "Barrow's Goldeneye" },
	BAHS: { name: "Bahama Swallow" },
	BAIS: { name: "Baird's Sparrow" },
	BAMO: { name: "Bahama Mockingbird" },
	BANA: { name: "Bananaquit" },
	BANP: { name: "Band-rumped Storm-Petrel" },
	BANS: { name: "Bank Swallow" },
	BAOR: { name: "Baltimore Oriole" },
	BARG: { name: "Bar-tailed Godwit" },
	BARS: { name: "Barn Swallow" },
	BASA: { name: "Baird's Sandpiper" },
	BATE: { name: "Baikal Teal" },
	BAWO: { name: "Bahama Woodstar" },
	BAWW: { name: "Black-and-white Warbler" },
	BAYE: { name: "Bahama Yellowthroat" },
	BBAL: { name: "Black-browed Albatross" },
	BBCU: { name: "Black-billed Cuckoo" },
	BBFL: { name: "Buff-breasted Flycatcher" },
	BBGR: { name: "Blue-black Grassquit" },
	BBLH: { name: "Broad-billed Hummingbird" },
	BBMA: { name: "Black-billed Magpie" },
	BBOH: { name: "Baltimore x Bullock's Oriole Hybrid" },
	BBPL: { name: "Black-bellied Plover" },
	BBPR: { name: "Broad-billed Prion" },
	BBRA: { name: "Buff-banded Rail" },
	BBSA: { name: "Buff-breasted Sandpiper" },
	BBWA: { name: "Bay-breasted Warbler" },
	BBWD: { name: "Black-bellied Whistling-Duck" },
	BBWO: { name: "Black-backed Woodpecker" },
	BCCH: { name: "Black-capped Chickadee" },
	BCFL: { name: "Brown-crested Flycatcher" },
	BCGN: { name: "Black-capped Gnatcatcher" },
	BCHU: { name: "Black-chinned Hummingbird" },
	BCLO: { name: "Blue-crowned Lorikeet" },
	BCNH: { name: "Black-crowned Night-Heron" },
	BCNI: { name: "Buff-collared Nightjar" },
	BCOR: { name: "Black-cowled Oriole" },
	BCPE: { name: "Black-capped Petrel" },
	BCRF: { name: "Brown-capped Rosy Finch" },
	BCSP: { name: "Black-chinned Sparrow" },
	BCTI: { name: "Black-crested Titmouse" },
	BCVI: { name: "Black-capped Vireo" },
	BDOW: { name: "Barred Owl" },
	BECO: { name: "Blue-eyed Cormorant" },
	BEHU: { name: "Berylline Hummingbird" },
	BEKI: { name: "Belted Kingfisher" },
	BESW: { name: "Bewick's Swan" },
	BETH: { name: "Bendire's Thrasher" },
	BEVI: { name: "Bell's Vireo" },
	BEWR: { name: "Bewick's Wren" },
	BFAL: { name: "Black-footed Albatross" },
	BFBO: { name: "Blue-footed Booby" },
	BFGR: { name: "Black-faced Grassquit" },
	BGGN: { name: "Blue-gray Gnatcatcher" },
	BGNO: { name: "Blue-gray Noddy" },
	BGSE: { name: "Blue Grouse" },
	BGSG: { name: "Blue Greater Snow Goose" },
	BHCO: { name: "Brown-headed Cowbird" },
	BHGR: { name: "Black-headed Grosbeak" },
	BHGU: { name: "Black-headed Gull" },
	BHNU: { name: "Brown-headed Nuthatch" },
	BHPA: { name: "Black-headed Parakeet" },
	BHVI: { name: "Blue-headed Vireo" },
	BIOO: { name: "Bishop's Oo" },
	BITH: { name: "Bicknell's Thrush" },
	BLAG: { name: "Black-tailed Godwit" },
	BLBR: { name: "Black Brant" },
	BLBU: { name: "Blue Bunting" },
	BLBW: { name: "Blackburnian Warbler" },
	BLDR: { name: "Black Drongo" },
	BLGO: { name: "Blue Goose" },
	BLGR: { name: "Blue Grosbeak" },
	BLGU: { name: "Black Guillemot" },
	BLJA: { name: "Blue Jay" },
	BLKI: { name: "Black-legged Kittiwake" },
	BLNO: { name: "Black Noddy" },
	BLOY: { name: "Black Oystercatcher" },
	BLPE: { name: "Blue Petrel" },
	BLPH: { name: "Black Phoebe" },
	BLPW: { name: "Blackpoll Warbler" },
	BLRA: { name: "Black Rail" },
	BLRF: { name: "Black Rosy-Finch" },
	BLSC: { name: "Black Scoter" },
	BLSK: { name: "Black Skimmer" },
	BLSP: { name: "Black Storm-Petrel" },
	BLSW: { name: "Black Swift" },
	BLTE: { name: "Black Tern" },
	BLTU: { name: "Black Turnstone" },
	BLUE: { name: "Bluethroat" },
	BLUH: { name: "Blue-throated Hummingbird" },
	BLVU: { name: "Black Vulture" },
	BNOW: { name: "Barn-Owl" },
	BNST: { name: "Black-necked Stilt" },
	BNTE: { name: "Black-naped Tern" },
	BOBO: { name: "Bobolink" },
	BOCH: { name: "Boreal Chickadee" },
	BOGU: { name: "Bonaparte's Gull" },
	BOOW: { name: "Boreal Owl" },
	BOPE: { name: "Bonin Petrel" },
	BOSP: { name: "Botteri's Sparrow" },
	BOWA: { name: "Bohemian Waxwing" },
	BRAC: { name: "Brandt's Cormorant" },
	BRAM: { name: "Brambling" },
	BRAN: { name: "Brant" },
	BRBL: { name: "Brewer's Blackbird" },
	BRBO: { name: "Brown Booby" },
	BRCR: { name: "Brown Creeper" },
	BRJA: { name: "Brown Jay" },
	BRMA: { name: "Bronze Mannikin" },
	BRNG: { name: "Barnacle Goose" },
	BRNO: { name: "Brown Noddy" },
	BROC: { name: "Bronzed Cowbird" },
	BRPE: { name: "Brown Pelican" },
	BRQD: { name: "Bridled Quail-Dove" },
	BRSH: { name: "Brown Shrike" },
	BRSK: { name: "Brown Skua" },
	BRSP: { name: "Brewer's Sparrow" },
	BRTE: { name: "Bridled Tern" },
	BRTH: { name: "Brown Thrasher" },
	BRTI: { name: "Bridled Titmouse" },
	BRTR: { name: "Brown Trembler" },
	BRWA: { name: "Brewster's Warbler" },
	BRWE: { name: "Bridled White-Eye" },
	BRWX: { name: "Black-rumped Waxbill" },
	BSSP: { name: "Belding's Savannah Sparrow" },
	BTBW: { name: "Black-throated Blue Warbler" },
	BTCU: { name: "Bristle-thighed Curlew" },
	BTGN: { name: "Black-tailed Gnatcatcher" },
	BTGR: { name: "Boat-tailed Grackle" },
	BTGU: { name: "Band-tailed Gull" },
	BTLH: { name: "Broad-tailed Hummingbird" },
	BTNW: { name: "Black-throated Green Warbler" },
	BTPA: { name: "Brown-throated Parakeet" },
	BTPI: { name: "Band-tailed Pigeon" },
	BTSP: { name: "Black-throated Sparrow" },
	BTYW: { name: "Black-throated Gray Warbler" },
	BUAL: { name: "Buller's Albatross" },
	BUFF: { name: "Bufflehead" },
	BUFH: { name: "Buff-bellied Hummingbird" },
	BUHU: { name: "Bumblebee Hummingbird" },
	BULS: { name: "Buller's Shearwater" },
	BUOR: { name: "Bullock's Oriole" },
	BUOW: { name: "Burrowing Owl" },
	BUPE: { name: "Bulwer's Petrel" },
	BUSH: { name: "Bushtit" },
	BVOR: { name: "Black-vented Oriole" },
	BVSH: { name: "Black-vented Shearwater" },
	BWAG: { name: "Black-backed Wagtail" },
	BWHA: { name: "Broad-winged Hawk" },
	BWPE: { name: "Black-winged Petrel" },
	BWTE: { name: "Blue-winged Teal" },
	BWVI: { name: "Black-whiskered Vireo" },
	BWWA: { name: "Blue-winged Warbler" },
	CAAU: { name: "Cassin's Auklet" },
	CACG: { name: "Cackling Goose" },
	CACH: { name: "Carolina Chickadee" },
	CACW: { name: "Cactus Wren" },
	CADO: { name: "Caribbean Dove" },
	CAEG: { name: "Cattle Egret" },
	CAEL: { name: "Caribbean Elaenia" },
	CAFI: { name: "Cassin's Finch" },
	CAGN: { name: "California Gnatcatcher" },
	CAGO: { name: "Canada Goose" },
	CAGU: { name: "California Gull" },
	CAHO: { name: "Cardinal Honeyeater" },
	CAHU: { name: "Calliope Hummingbird" },
	CAKI: { name: "Cassin's Kingbird" },
	CALC: { name: "California Condor" },
	CALT: { name: "California Towhee" },
	CAMA: { name: "Caribbean Martin" },
	CANT: { name: "Canyon Towhee" },
	CANV: { name: "Canvasback" },
	CANW: { name: "Canyon Wren" },
	CAPE: { name: "Cape Petrel" },
	CAQU: { name: "California Quail" },
	CARC: { name: "Caribbean Coot" },
	CARW: { name: "Carolina Wren" },
	CASP: { name: "Cassin's Sparrow" },
	CASW: { name: "Cave Swallow" },
	CATE: { name: "Caspian Tern" },
	CATH: { name: "California Thrasher" },
	CAVI: { name: "Cassin's Vireo" },
	CAWA: { name: "Canada Warbler" },
	CAYT: { name: "Cayenne Tern" },
	CBCH: { name: "Chestnut-backed Chickadee" },
	CBTH: { name: "Curve-billed Thrasher" },
	CCLO: { name: "Chestnut-collared Longspur" },
	CCSP: { name: "Clay-colored Sparrow" },
	CCTH: { name: "Clay-colored Thrush" },
	CEDW: { name: "Cedar Waxwing" },
	CERW: { name: "Cerulean Warbler" },
	CHCO: { name: "Cherry-head Conure" },
	CHPE: { name: "Chinstrap Penguin" },
	CHRA: { name: "Chihuahuan Raven" },
	CHSH: { name: "Christmas Shearwater" },
	CHSP: { name: "Chipping Sparrow" },
	CHSW: { name: "Chimney Swift" },
	CHUK: { name: "Chukar" },
	CITE: { name: "Cinnamon Teal" },
	CLGR: { name: "Clark's Grebe" },
	CLNU: { name: "Clark's Nutcracker" },
	CLRA: { name: "Clapper Rail" },
	CLSW: { name: "Cliff Swallow" },
	CLTE: { name: "California Least Tern" },
	CMWA: { name: "Cape May Warbler" },
	COBH: { name: "Common Black-Hawk" },
	COCA: { name: "Common Canary" },
	COCH: { name: "Common Chaffinch" },
	COEI: { name: "Common Eider" },
	COFL: { name: "Cordilleran Flycatcher" },
	COGA: { name: "Common Gallinule" },
	COGD: { name: "Common Ground-Dove" },
	COGO: { name: "Common Goldeneye" },
	COGR: { name: "Common Grackle" },
	COHA: { name: "Cooper's Hawk" },
	COHU: { name: "Costa's Hummingbird" },
	COKI: { name: "Couch's Kingbird" },
	COLK: { name: "Collared Kingfisher" },
	COLO: { name: "Common Loon" },
	COLW: { name: "Colima Warbler" },
	COME: { name: "Common Merganser" },
	COMO: { name: "Common Moorhen" },
	COMP: { name: "Common Peafowl" },
	COMU: { name: "Common Murre" },
	COMW: { name: "Common Waxbill" },
	COMY: { name: "Common Myna" },
	CONI: { name: "Common Nighthawk" },
	CONW: { name: "Connecticut Warbler" },
	COPA: { name: "Common Pauraque" },
	COPE: { name: "Cook's Petrel" },
	COPO: { name: "Common Poorwill" },
	CORA: { name: "Common Raven" },
	CORE: { name: "Common Redpoll" },
	CORO: { name: "Common Rosefinch" },
	COSA: { name: "Common Sandpiper" },
	COSH: { name: "Cory's Shearwater" },
	COSN: { name: "Common Snipe" },
	COTE: { name: "Common Tern" },
	COYE: { name: "Common Yellowthroat" },
	CPOC: { name: "Common Pochard" },
	CRAU: { name: "Crested Auklet" },
	CRCA: { name: "Crested Caracara" },
	CRMU: { name: "Craveri's Murrelet" },
	CRMY: { name: "Crested Myna" },
	CRPL: { name: "Common Ringed Plover" },
	CRTE: { name: "Crested Tern" },
	CRTH: { name: "Crissal Thrasher" },
	CSOW: { name: "California Spotted Owl" },
	CSSS: { name: "Cape Sable Seaside Sparrow" },
	CSWA: { name: "Chestnut-sided Warbler" },
	CUGR: { name: "Cuban Grassquit" },
	CUPE: { name: "Cuban Antillean Pewee" },
	CUSA: { name: "Curlew Sandpiper" },
	CWWI: { name: "Chuck-will's-widow" },
	DCCO: { name: "Double-crested Cormorant" },
	DCFL: { name: "Dusky-capped Flycatcher" },
	DEJU: { name: "Dark-eyed Junco" },
	DICK: { name: "Dickcissel" },
	DOPR: { name: "Dove Prion" },
	DOVE: { name: "Dovekie" },
	DOWO: { name: "Downy Woodpecker" },
	DSFL: { name: "Dark-sided Flycatcher" },
	DSSP: { name: "Dusky Seaside Sparrow" },
	DUFL: { name: "Dusky Flycatcher" },
	DUNL: { name: "Dunlin" },
	DUTH: { name: "Dusky Thrush" },
	DUWA: { name: "Dusky Warbler" },
	EABL: { name: "Eastern Bluebird" },
	EAGR: { name: "Eared Grebe" },
	EAKI: { name: "Eastern Kingbird" },
	EAME: { name: "Eastern Meadowlark" },
	EAPH: { name: "Eastern Phoebe" },
	EAQU: { name: "Eared Quetzal" },
	EASO: { name: "Eastern Screech-Owl" },
	EATO: { name: "Eastern Towhee" },
	EAWP: { name: "Eastern Wood-Pewee" },
	ECDO: { name: "Eurasian Collared-Dove" },
	EGWT: { name: "European Green-winged Teal" },
	ELOW: { name: "Elf Owl" },
	ELTE: { name: "Elegant Tern" },
	ELTR: { name: "Elegant Trogon" },
	EMGO: { name: "Emperor Goose" },
	EMPE: { name: "Emperor Penguin" },
	ETSP: { name: "European Tree Sparrow" },
	EUBU: { name: "Eurasian Bullfinch" },
	EUDO: { name: "Eurasian Dotterel" },
	EUGO: { name: "European Goldfinch" },
	EUGP: { name: "Eurasian Golden-Plover" },
	EUKE: { name: "Eurasian Kestrel" },
	EUST: { name: "European Starling" },
	EUWI: { name: "Eurasian Wigeon" },
	EUWO: { name: "European Woodcock" },
	EVGR: { name: "Evening Grosbeak" },
	EWCS: { name: "Eastern White-crowned Sparrow" },
	EWPW: { name: "Eastern Whip-poor-will" },
	EWWA: { name: "Elfin-woods Warbler" },
	EYTH: { name: "Eyebrowed Thrush" },
	EYWA: { name: "Eastern Yellow Wagtail" },
	FAPE: { name: "Fairy Penguin" },
	FAPR: { name: "Fairy Prion" },
	FATE: { name: "Falcated Teal" },
	FCTA: { name: "Flame-colored Tanager" },
	FEHA: { name: "Ferruginous Hawk" },
	FEPO: { name: "Ferruginous Pygmy-Owl" },
	FFSH: { name: "Flesh-footed Shearwater" },
	FGSP: { name: "Florida Grasshopper Sparrow" },
	FICR: { name: "Fish Crow" },
	FIEL: { name: "Fieldfare" },
	FISH: { name: "Fiji Shrikebill" },
	FISP: { name: "Field Sparrow" },
	FLIN: { name: "Flicker Intergrade" },
	FLOW: { name: "Flammulated Owl" },
	FLSJ: { name: "Florida Scrub-Jay" },
	FOSP: { name: "Fox Sparrow" },
	FOTE: { name: "Forster's Tern" },
	FRGU: { name: "Franklin's Gull" },
	FSSP: { name: "Five-striped Sparrow" },
	FTFL: { name: "Fork-tailed Flycatcher" },
	FTSP: { name: "Fork-tailed Storm-Petrel" },
	FTWA: { name: "Fan-tailed Warbler" },
	FUWD: { name: "Fulvous Whistling-Duck" },
	GABU: { name: "Greater Antillean Bullfinch" },
	GADW: { name: "Gadwall" },
	GAEL: { name: "Greater Antillean Elaenia" },
	GAGR: { name: "Greater Antillean Grackle" },
	GALP: { name: "Galapogos Penguin" },
	GAQU: { name: "Gambel's Quail" },
	GARG: { name: "Garganey" },
	GBAN: { name: "Groove-billed Ani" },
	GBBG: { name: "Great Black-backed Gull" },
	GBHE: { name: "Great Blue Heron" },
	GBMA: { name: "Gray-breasted Martin" },
	GBSP: { name: "Gray-backed Storm-Petrel" },
	GBTE: { name: "Gull-billed Tern" },
	GCBT: { name: "Unspecified Bicknell's Or Gray-cheeked Thrush" },
	GCFL: { name: "Great-crested Flycatcher" },
	GCKI: { name: "Golden-crowned Kinglet" },
	GCRF: { name: "Gray-crowned Rosy Finch" },
	GCSP: { name: "Golden-crowned Sparrow" },
	GCTH: { name: "Gray-cheeked Thrush" },
	GCWA: { name: "Golden-cheeked Warbler" },
	GCYE: { name: "Gray-crowned Yellowthroat" },
	GEPE: { name: "Gentoo Penguin" },
	GFWO: { name: "Golden-fronted Woodpecker" },
	GGOW: { name: "Great Gray Owl" },
	GHAL: { name: "Gray-headed Albatross" },
	GHCH: { name: "Gray-headed Chickadee" },
	GHJU: { name: "Gray-headed Junco" },
	GHOW: { name: "Great Horned Owl" },
	GIFL: { name: "Gilded Flicker" },
	GIWO: { name: "Gila Woodpecker" },
	GKIN: { name: "Green Kingfisher" },
	GKIS: { name: "Great Kiskadee" },
	GLGU: { name: "Glaucous Gull" },
	GLIB: { name: "Glossy Ibis" },
	GNLA: { name: "Greater Necklaced Laughingthrush" },
	GOEA: { name: "Golden Eagle" },
	GOLW: { name: "Golden-crowned Warbler" },
	GOWE: { name: "Golden White-Eye" },
	GPCH: { name: "Greater Prairie-Chicken" },
	GRAJ: { name: "Gray Jay" },
	GRAK: { name: "Gray Kingbird" },
	GRAT: { name: "Gray-backed Tern" },
	GRAW: { name: "Gray Wagtail" },
	GRBU: { name: "Gray Bunting" },
	GRCA: { name: "Gray Catbird" },
	GRCO: { name: "Great Cormorant" },
	GREG: { name: "Great Egret" },
	GREJ: { name: "Green Jay" },
	GREL: { name: "Greenish Elaenia" },
	GREM: { name: "Green-breasted Mango" },
	GRFL: { name: "Gray Flycatcher" },
	GRFR: { name: "Great Frigatebird" },
	GRGO: { name: "Greylag Goose" },
	GRHA: { name: "Gray Hawk" },
	GRHE: { name: "Green Heron" },
	GRMA: { name: "Green Mango" },
	GRPA: { name: "Gray Partridge" },
	GRPE: { name: "Greater Pewee" },
	GRRO: { name: "Greater Roadrunner" },
	GRSC: { name: "Greater Scaup" },
	GRSG: { name: "Greater Sage Grouse" },
	GRSH: { name: "Great Shearwater" },
	GRSK: { name: "Great Skua" },
	GRSP: { name: "Grasshopper Sparrow" },
	GRVI: { name: "Gray Vireo" },
	GRWA: { name: "Grace's Warbler" },
	GRYE: { name: "Greater Yellowlegs" },
	GSFL: { name: "Gray-streaked Flycatcher" },
	GSGO: { name: "Greater Snow Goose" },
	GTCA: { name: "Green-throated Carib" },
	GTGR: { name: "Great-tailed Grackle" },
	GTTA: { name: "Gray-tailed Tattler" },
	GTTO: { name: "Green-tailed Towhee" },
	GUCO: { name: "Guanay Cormorant" },
	GUSG: { name: "Gunnison Sage-Grouse" },
	GUSW: { name: "Guam Swiftlet" },
	GVIO: { name: "Green Violetear" },
	GWCS: { name: "Gambel's White-crowned Sparrow" },
	GWFG: { name: "Greater White-fronted Goose" },
	GWGU: { name: "Glaucous-winged Gull" },
	GWHE: { name: "Great White Heron" },
	GWTE: { name: "Green-winged Teal" },
	GWWA: { name: "Golden-winged Warbler" },
	GYRF: { name: "Gyrfalcon" },
	HAAM: { name: "Hawaiʻi ʻAmakihi" },
	HACO: { name: "Hawaiian Coot" },
	HAEL: { name: "Hawaiʻi ‘Elepaio" },
	HAFL: { name: "Hammond's Flycatcher" },
	HAGA: { name: "Hawaiian Gallinule" },
	HAGO: { name: "Hawaiian Goose" },
	HAPE: { name: "Hawaiian Petrel" },
	HARD: { name: "Harlequin Duck" },
	HASP: { name: "Harris's Sparrow" },
	HAST: { name: "Hawaiian Stilt" },
	HAWD: { name: "Hawaiian Duck" },
	HAWF: { name: "Hawfinch" },
	HAWO: { name: "Hairy Woodpecker" },
	HBKI: { name: "Hook-billed Kite" },
	HCRE: { name: "Hawaiʻi Creeper" },
	HCRO: { name: "Hawaiian Crow" },
	HCRT: { name: "Common Tern x Roseate Tern Hybrid" },
	HEEG: { name: "Heermann's Gull" },
	HERG: { name: "Herring Gull" },
	HESP: { name: "Henslow's Sparrow" },
	HETA: { name: "Hepatic Tanager" },
	HETH: { name: "Hermit Thrush" },
	HEWA: { name: "Hermit Warbler" },
	HIMY: { name: "Hill Myna" },
	HIPE: { name: "Hispaniolan Pewee" },
	HOFI: { name: "House Finch" },
	HOGR: { name: "Horned Grebe" },
	HOLA: { name: "Horned Lark" },
	HOME: { name: "Hooded Merganser" },
	HOOR: { name: "Hooded Oriole" },
	HOPU: { name: "Horned Puffin" },
	HORE: { name: "Hoary Redpoll" },
	HOSP: { name: "House Sparrow" },
	HOWA: { name: "Hooded Warbler" },
	HOWR: { name: "House Wren" },
	HPKT: { name: "Hispaniolan Parakeet" },
	HPRT: { name: "Hispaniolan Parrot" },
	HRLH: { name: "Harlan's Hawk" },
	HRSH: { name: "Harris's Hawk" },
	HUGO: { name: "Hudsonian Godwit" },
	HUPE: { name: "Humboldt Penguin" },
	HUVI: { name: "Hutton's Vireo" },
	HWAM: { name: "Hwamei" },
	HWHA: { name: "Hawaiian Hawk" },
	HYAL: { name: "Hybrid Albatross" },
	HYBL: { name: "Hybrid Bluebird" },
	HYCH: { name: "Hybrid Chickadee" },
	HYGU: { name: "Hybrid Gull" },
	HYHU: { name: "Hybrid Hummingbird" },
	HYNO: { name: "Hybrid Nonpasserine" },
	HYPA: { name: "Hybrid Passerine" },
	HYSA: { name: "Hybrid Sapsucker" },
	HYSK: { name: "Hybrid Skua" },
	HYTE: { name: "Hybrid Tern" },
	HYTO: { name: "Hybrid Towhee" },
	HYWA: { name: "Hybrid Warbler" },
	IBWO: { name: "Ivory-billed Woodpecker" },
	ICGU: { name: "Iceland Gull" },
	ICTO: { name: "Inyo California Towhee" },
	IIWI: { name: "ʻIʻiwi" },
	ILBH: { name: "Indigo x Lazuli Bunting Hybrid" },
	ILTE: { name: "Interior Least Tern" },
	INBU: { name: "Indigo Bunting" },
	INDO: { name: "Inca Dove" },
	IPSP: { name: "Ipswich Sparrow" },
	ISSJ: { name: "Island Scrub-Jay" },
	IVGU: { name: "Ivory Gull" },
	JABW: { name: "Japanese Bush-Warbler" },
	JACR: { name: "Jamaican Crow" },
	JAEL: { name: "Jamaican Elaenia" },
	JAEU: { name: "Jamaican Euphonia" },
	JAMA: { name: "Jamaican Mango" },
	JAOR: { name: "Jamaican Oriole" },
	JAPE: { name: "Jamaican Pewee" },
	JASP: { name: "Java Sparrow" },
	JATO: { name: "Jamaican Tody" },
	JAVI: { name: "Jamaican Vireo" },
	JAWE: { name: "Japanese White-Eye" },
	JFPE: { name: "Juan Fernandez Petrel" },
	JUMY: { name: "Jungle Myna" },
	JUTI: { name: "Juniper Titmouse" },
	KAAK: { name: "Kauaʻi ʻAkialoa" },
	KAAM: { name: "Kauaʻi ʻAmakihi" },
	KAEL: { name: "Kauaʻi ‘Elepaio" },
	KAKA: { name: "Kākāwahie" },
	KAMA: { name: "Kāmaʻo" },
	KAOO: { name: "Kauaʻi ʻŌʻō" },
	KEPE: { name: "Kerguelen Petrel" },
	KETE: { name: "Kerguelen Tern" },
	KEWA: { name: "Kentucky Warbler" },
	KIEI: { name: "King Eider" },
	KILL: { name: "Killdeer" },
	KIMU: { name: "Kittlitz's Murrelet" },
	KIPE: { name: "King Penguin" },
	KIRA: { name: "King Rail" },
	KIWA: { name: "Kirtland's Warbler" },
	KWQD: { name: "Key West Quail-Dove" },
	LAAL: { name: "Laysan Albatross" },
	LADU: { name: "Laysan Duck" },
	LAFI: { name: "Laysan Finch" },
	LAGO: { name: "Lawrence's Goldfinch" },
	LAGU: { name: "Laughing Gull" },
	LALO: { name: "Lapland Longspur" },
	LANW: { name: "Lanceolate Warbler" },
	LAPE: { name: "Lesser Antillean Pewee" },
	LARB: { name: "Lark Bunting" },
	LASP: { name: "Lark Sparrow" },
	LAVW: { name: "Lavender Waxbill" },
	LAWA: { name: "Lawrence's Warbler" },
	LAZB: { name: "Lazuli Bunting" },
	LBBG: { name: "Lesser Black-backed Gull" },
	LBCU: { name: "Long-billed Curlew" },
	LBDO: { name: "Long-billed Dowitcher" },
	LBHE: { name: "Little Blue Heron" },
	LBMU: { name: "Long-billed Murrelet" },
	LBSP: { name: "Large-billed Sparrow" },
	LBTH: { name: "Long-billed Thrasher" },
	LBVI: { name: "Least Bell's Vireo" },
	LBWO: { name: "Ladder-backed Woodpecker" },
	LCGO: { name: "Large Canada Goose" },
	LCSP: { name: "Le Conte's Sparrow" },
	LCTH: { name: "Le Conte's Thrasher" },
	LEAU: { name: "Least Auklet" },
	LEBI: { name: "Least Bittern" },
	LEFL: { name: "Least Flycatcher" },
	LEFR: { name: "Lesser Frigatebird" },
	LEGO: { name: "Lesser Goldfinch" },
	LEGP: { name: "Lesser Golden-Plover" },
	LEGR: { name: "Least Grebe" },
	LENI: { name: "Lesser Nighthawk" },
	LEOW: { name: "Long-eared Owl" },
	LESA: { name: "Least Sandpiper" },
	LESB: { name: "Lesser Antillean Bullfinch" },
	LESC: { name: "Lesser Scaup" },
	LESF: { name: "Lesser Antillean Flycatcher" },
	LESH: { name: "Lesser Sheathbill" },
	LETE: { name: "Least Tern" },
	LEWO: { name: "Lewis's Woodpecker" },
	LEYE: { name: "Lesser Yellowlegs" },
	LHSP: { name: "Leach's Storm-Petrel" },
	LIBU: { name: "Little Bunting" },
	LIGU: { name: "Little Gull" },
	LIMP: { name: "Limpkin" },
	LISH: { name: "Little Shearwater" },
	LISP: { name: "Lincoln's Sparrow" },
	LITE: { name: "Little Tern" },
	LMSA: { name: "Light-mantled Sooty Albatross" },
	LOKI: { name: "Loggerhead Kingbird" },
	LOSH: { name: "Loggerhead Shrike" },
	LOWA: { name: "Louisiana Waterthrush" },
	LPCH: { name: "Lesser Prairie-Chicken" },
	LRSP: { name: "Lesser Sand Plover" },
	LSFL: { name: "La Sagra's Flycatcher" },
	LSGO: { name: "Lesser Snow Goose" },
	LTCU: { name: "Long Tail Cuckoo" },
	LTDU: { name: "Long-tailed Duck" },
	LTJA: { name: "Long-tailed Jaeger" },
	LTSP: { name: "Least Storm-Petrel" },
	LTST: { name: "Long-toed Stint" },
	LUHU: { name: "Lucifer Hummingbird" },
	LUWA: { name: "Lucy's Warbler" },
	LWFG: { name: "Lesser White-fronted Goose" },
	MAAL: { name: "Maui 'Alauahio" },
	MABO: { name: "Masked Booby" },
	MACP: { name: "Macaroni Penguin" },
	MACU: { name: "Mangrove Cuckoo" },
	MADU: { name: "Masked Duck" },
	MAFD: { name: "Marianas Fruit-Dove" },
	MAFR: { name: "Magnificent Frigatebird" },
	MAGO: { name: "Marbled Godwit" },
	MAGP: { name: "Magellanic Penguin" },
	MAGU: { name: "Magellan Gull" },
	MAHU: { name: "Magnificent Hummingbird" },
	MALL: { name: "Mallard" },
	MALX: { name: "Mallard Dominant x American Black Duck Hybrid" },
	MAMU: { name: "Marbled Murrelet" },
	MAPA: { name: "Maui Parrotbill" },
	MARC: { name: "Mariana Crow" },
	MASA: { name: "Marsh Sandpiper" },
	MASH: { name: "Manx Shearwater" },
	MASW: { name: "Mariana Swiftlet" },
	MAWA: { name: "Magnolia Warbler" },
	MAWR: { name: "Marsh Wren" },
	MBDH: { name: "Mallard x American Black Duck Hybrid" },
	MBDX: { name: "Mallard x American Black Duck Intermediate" },
	MCFD: { name: "Many-colored Fruit Dove" },
	MCLO: { name: "McCown's Longspur" },
	MECH: { name: "Mexican Chickadee" },
	MEDU: { name: "Mexican Duck" },
	MEGU: { name: "Mew Gull" },
	MEJA: { name: "Mexican Jay" },
	MERL: { name: "Merlin" },
	MGWA: { name: "Macgillivray's Warbler" },
	MICK: { name: "Micronesian Kingfisher" },
	MIGW: { name: "Middendorff's Grasshopper-Warbler" },
	MIHO: { name: "Micronesian Honeyeater" },
	MIKI: { name: "Mississippi Kite" },
	MILL: { name: "Millerbird" },
	MIME: { name: "Micronesian Megapode" },
	MIST: { name: "Micronesian Starling" },
	MKBU: { name: "McKay's Bunting" },
	MOBL: { name: "Mountain Bluebird" },
	MOCH: { name: "Mountain Chickadee" },
	MODO: { name: "Mourning Dove" },
	MODU: { name: "Mottled Duck" },
	MOPA: { name: "Monk Parakeet" },
	MOPE: { name: "Mottled Petrel" },
	MOPL: { name: "Mountain Plover" },
	MOUQ: { name: "Mountain Quail" },
	MOWA: { name: "Mourning Warbler" },
	MSCR: { name: "Mississippi Sandhill Crane" },
	MSOW: { name: "Mexican Spotted Owl" },
	MTZQ: { name: "Montezuma's Quail" },
	MUDU: { name: "Muscovy Duck" },
	MUPE: { name: "Murphy's Petrel" },
	MUSW: { name: "Mute Swan" },
	MWCS: { name: "Mountain White-crowned Sparrow" },
	MWPW: { name: "Mexican Whip-poor-will" },
	MYWA: { name: "Myrtle Warbler" },
	NABO: { name: "Nazca Booby" },
	NAWA: { name: "Nashville Warbler" },
	NBTY: { name: "Northern Beardless Tyrannulet" },
	NECO: { name: "Neotropic Cormorant" },
	NESH: { name: "Newell's Shearwater" },
	NESP: { name: "Nelson's Sparrow" },
	NGPE: { name: "Northern Giant Petrel" },
	NHOW: { name: "Northern Hawk Owl" },
	NIFI: { name: "Nihoa Finch" },
	NIRW: { name: "Nightingale Reed-Warbler" },
	NOBO: { name: "Northern Bobwhite" },
	NOCA: { name: "Northern Cardinal" },
	NOCR: { name: "Northwestern Crow" },
	NOFL: { name: "Northern Flicker" },
	NOFU: { name: "Northern Fulmar" },
	NOGA: { name: "Northern Gannet" },
	NOGO: { name: "Northern Goshawk" },
	NOHA: { name: "Northern Harrier" },
	NOJA: { name: "Northern Jacana" },
	NOLA: { name: "Northern Lapwing" },
	NOMO: { name: "Northern Mockingbird" },
	NOPA: { name: "Northern Parula" },
	NOPI: { name: "Northern Pintail" },
	NOPO: { name: "Northern Pygmy-Owl" },
	NOWA: { name: "Northern Waterthrush" },
	NOWH: { name: "Northern Wheatear" },
	NRWS: { name: "Northern Rough-winged Swallow" },
	NSHO: { name: "Northern Shoveler" },
	NSHR: { name: "Northern Shrike" },
	NSOW: { name: "Northern Spotted Owl" },
	NSWO: { name: "Northern Saw-whet Owl" },
	NUFL: { name: "Nutting's Flycatcher" },
	NUKU: { name: "Nukupu‘u" },
	NUMA: { name: "Nutmeg Mannikin" },
	NUWO: { name: "Nuttall's Woodpecker" },
	NWCS: { name: "Nuttall's White-crowned Sparrow" },
	OAAL: { name: "Oʻahu ʻAlauahio" },
	OAAM: { name: "Oʻahu ʻAmakihi" },
	OAEL: { name: "O'ahu ‘Elepaio" },
	OATI: { name: "Oak Titmouse" },
	OBNT: { name: "Orange-billed Nightingale-Thrush" },
	OBPI: { name: "Olive-backed Pipit" },
	OCWA: { name: "Orange-crowned Warbler" },
	OFPA: { name: "Orange-fronted Parakeet" },
	OHDU: { name: "Other Hybrid Duck" },
	OHGO: { name: "Other Hybrid Goose" },
	OLIW: { name: "Olive-capped Warbler" },
	OLOM: { name: "Olomaʻo" },
	OLSP: { name: "Olive Sparrow" },
	OLWA: { name: "Olive Warbler" },
	OMAO: { name: "ʻŌmaʻo" },
	ORAN: { name: "Orangequit" },
	ORAW: { name: "Orange-cheeked Waxbill" },
	ORGR: { name: "Oriental Greenfinch" },
	ORJU: { name: "Oregon Junco" },
	OROR: { name: "Orchard Oriole" },
	OSFL: { name: "Olive-sided Flycatcher" },
	OSPR: { name: "Osprey" },
	OU: { name: "ʻŌʻū" },
	OVEN: { name: "Ovenbird" },
	OWPA: { name: "Orange-winged Parrot" },
	PAAU: { name: "Parakeet Auklet" },
	PABU: { name: "Painted Bunting" },
	PAGP: { name: "Pacific Golden-Plover" },
	PAJA: { name: "Parasitic Jaeger" },
	PALB: { name: "Pallas's Bunting" },
	PALI: { name: "Palila" },
	PALO: { name: "Pacific Loon" },
	PAPI: { name: "Pacific Pigeon" },
	PARE: { name: "Painted Redstart" },
	PAWA: { name: "Palm Warbler" },
	PAWR: { name: "Pacific Wren" },
	PBGR: { name: "Pied-billed Grebe" },
	PBWH: { name: "Puerto Rican Broad-winged Hawk" },
	PCFD: { name: "Purple-collared Fruit-Dove" },
	PCST: { name: "Plain-capped Starthroat" },
	PECO: { name: "Pelagic Cormorant" },
	PEFA: { name: "Peregrine Falcon" },
	PEPI: { name: "Pechora Pipit" },
	PESA: { name: "Pectoral Sandpiper" },
	PETH: { name: "Pearly-eyed Thrasher" },
	PFGO: { name: "Pink-footed Goose" },
	PFSH: { name: "Pink-footed Shearwater" },
	PHAI: { name: "Phainopepla" },
	PHPE: { name: "Phoenix Petrel" },
	PHTD: { name: "Philippine Turtle-Dove" },
	PHVI: { name: "Philadelphia Vireo" },
	PIGR: { name: "Pine Grosbeak" },
	PIGU: { name: "Pigeon Guillemot" },
	PIJA: { name: "Pinyon Jay" },
	PIPL: { name: "Piping Plover" },
	PISI: { name: "Pine Siskin" },
	PIWA: { name: "Pine Warbler" },
	PIWO: { name: "Pileated Woodpecker" },
	PLCH: { name: "Plain Chachalaca" },
	PLPI: { name: "Plain Pigeon" },
	PLTI: { name: "Plain Titmouse" },
	PLVI: { name: "Plumbeous Vireo" },
	POJA: { name: "Pomarine Jaeger" },
	POST: { name: "Polynesian Starling" },
	POUL: { name: "Poʻouli" },
	PRAW: { name: "Prairie Warbler" },
	PREM: { name: "Puerto Rican Emerald" },
	PRFA: { name: "Prairie Falcon" },
	PRFL: { name: "Puerto Rican Flycatcher" },
	PRLC: { name: "Puerto Rican Lizard Cuckoo" },
	PRNI: { name: "Puerto Rican Nightjar" },
	PROW: { name: "Prothonotary Warbler" },
	PRPA: { name: "Puerto Rican Parrot" },
	PRSO: { name: "Puerto Rican Screech-Owl" },
	PRTA: { name: "Puerto Rican Tanager" },
	PRTO: { name: "Puerto Rican Tody" },
	PRVI: { name: "Puerto Rican Vireo" },
	PRWO: { name: "Puerto Rican Woodpecker" },
	PSFL: { name: "Pacific Slope Flycatcher" },
	PSSH: { name: "Puerto Rican Sharp-shinned Hawk" },
	PSWS: { name: "Puget Sound White-crowned Sparrow" },
	PTSN: { name: "Pin-tailed Snipe" },
	PTWH: { name: "Pin-tailed Whydah" },
	PUAI: { name: "Puaiohi" },
	PUEB: { name: "Puerto Rican Bullfinch" },
	PUFI: { name: "Purple Finch" },
	PUGA: { name: "Purple Gallinule" },
	PUMA: { name: "Purple Martin" },
	PUSA: { name: "Purple Sandpiper" },
	PUSW: { name: "Purple Swamphen" },
	PYNU: { name: "Pygmy Nuthatch" },
	PYRR: { name: "Pyrrhuloxia" },
	RAZO: { name: "Razorbill" },
	RBGR: { name: "Rose-breasted Grosbeak" },
	RBGU: { name: "Ring-billed Gull" },
	RBLE: { name: "Red-billed Leiothrix" },
	RBME: { name: "Red-breasted Merganser" },
	RBNU: { name: "Red-breasted Nuthatch" },
	RBPI: { name: "Red-billed Pigeon" },
	RBRO: { name: "Rufous-backed Robin" },
	RBSA: { name: "Red-breasted Sapsucker" },
	RBTR: { name: "Red-billed Tropicbird" },
	RBWE: { name: "Rota Bridled White-Eye" },
	RBWO: { name: "Red-bellied Woodpecker" },
	RCCA: { name: "Red-crested Cardinal" },
	RCCO: { name: "Red-cheeked Cordonbleu" },
	RCKI: { name: "Ruby-crowned Kinglet" },
	RCPA: { name: "Red-crowned Parrot" },
	RCSP: { name: "Rufous-crowned Sparrow" },
	RCWA: { name: "Rufous-capped Warbler" },
	RCWO: { name: "Red-cockaded Woodpecker" },
	REAV: { name: "Red Avadavat" },
	REBI: { name: "Red Bishop" },
	REBU: { name: "Reed Bunting" },
	RECR: { name: "Red Crossbill" },
	REDH: { name: "Redhead" },
	REDW: { name: "Redwing" },
	REEG: { name: "Reddish Egret" },
	REHE: { name: "Reef Heron" },
	REKN: { name: "Red Knot" },
	REPH: { name: "Red Phalarope" },
	RESI: { name: "Red Siskin" },
	REVI: { name: "Red-eyed Vireo" },
	RFBL: { name: "Red-flanked Bluetail" },
	RFBO: { name: "Red-footed Booby" },
	RFCO: { name: "Red-faced Cormorant" },
	RFWA: { name: "Red-faced Warbler" },
	RHAU: { name: "Rhinoceros Auklet" },
	RHWO: { name: "Red-headed Woodpecker" },
	RIKI: { name: "Ringed Kingfisher" },
	RLHA: { name: "Rough-legged Hawk" },
	RLKI: { name: "Red-legged Kittiwake" },
	RLTH: { name: "Red-legged Thrush" },
	RNDU: { name: "Ring-necked Duck" },
	RNGR: { name: "Red-necked Grebe" },
	RNPH: { name: "Red-necked Phalarope" },
	RNSA: { name: "Red-naped Sapsucker" },
	RNST: { name: "Red-necked Stint" },
	ROAL: { name: "Royal Albatross" },
	ROCP: { name: "Rockhopper Penguin" },
	ROGO: { name: "Ross's Goose" },
	ROGU: { name: "Ross's Gull" },
	ROHA: { name: "Roadside Hawk" },
	ROPI: { name: "Rock Pigeon" },
	ROPT: { name: "Rock Ptarmigan" },
	ROSA: { name: "Rock Sandpiper" },
	ROSP: { name: "Roseate Spoonbill" },
	ROST: { name: "Roseate Tern" },
	ROWR: { name: "Rock Wren" },
	ROYP: { name: "Royal Penguin" },
	ROYT: { name: "Royal Tern" },
	RPHE: { name: "Ring-necked Pheasant" },
	RSFL: { name: "Red-shafted Flicker" },
	RSHA: { name: "Red-shouldered Hawk" },
	RTBE: { name: "Rose-throated Becard" },
	RTHA: { name: "Red-tailed Hawk" },
	RTHU: { name: "Ruby-throated Hummingbird" },
	RTLO: { name: "Red-throated Loon" },
	RTPI: { name: "Red-throated Pipit" },
	RTSO: { name: "Rufous-throated Solitaire" },
	RTTR: { name: "Red-tailed Tropicbird" },
	RUBL: { name: "Rusty Blackbird" },
	RUBU: { name: "Rustic Bunting" },
	RUDU: { name: "Ruddy Duck" },
	RUFA: { name: "Rufous Fantail" },
	RUFF: { name: "Ruff" },
	RUFH: { name: "Rufous-tailed Hummingbird" },
	RUFS: { name: "Rufous-collared Sparrow" },
	RUGD: { name: "Ruddy Ground-Dove" },
	RUGR: { name: "Ruffed Grouse" },
	RUHU: { name: "Rufous Hummingbird" },
	RUQD: { name: "Ruddy Quail-Dove" },
	RUTU: { name: "Ruddy Turnstone" },
	RVBU: { name: "Red-vented Bulbul" },
	RWBL: { name: "Red-winged Blackbird" },
	RWBU: { name: "Red-whiskered Bulbul" },
	RWSP: { name: "Rufous-winged Sparrow" },
	SACR: { name: "Sandhill Crane" },
	SAFI: { name: "Saffron Finch" },
	SAFL: { name: "Sad Flycatcher" },
	SAGS: { name: "Sage Sparrow" },
	SAGU: { name: "Sabine's Gull" },
	SALS: { name: "Saltmarsh Sparrow" },
	SAND: { name: "Sanderling" },
	SAPH: { name: "Say's Phoebe" },
	SAST: { name: "Samoan Starling" },
	SATE: { name: "Sandwich Tern" },
	SATH: { name: "Sage Thrasher" },
	SAVS: { name: "Savannah Sparrow" },
	SBAN: { name: "Smooth-billed Ani" },
	SBBG: { name: "Southern Black-backed Gull" },
	SBDO: { name: "Short-billed Dowitcher" },
	SBFL: { name: "Sulphur-bellied Flycatcher" },
	SBGI: { name: "Snow x Blue Goose Intergrade" },
	SBGU: { name: "Slaty-backed Gull" },
	SBOH: { name: "Spotted x Barred Owl Hybrid" },
	SCGO: { name: "Small Canada Goose" },
	SCIB: { name: "Scarlet Ibis" },
	SCJU: { name: "Slate-colored Junco" },
	SCOR: { name: "Scott's Oriole" },
	SCQU: { name: "Scaled Quail" },
	SCTA: { name: "Scarlet Tanager" },
	SEOW: { name: "Short-eared Owl" },
	SEPL: { name: "Semipalmated Plover" },
	SESA: { name: "Semipalmated Sandpiper" },
	SESP: { name: "Seaside Sparrow" },
	SEWR: { name: "Sedge Wren" },
	SGPE: { name: "Southern Giant Petrel" },
	SHAL: { name: "Shy Albatross" },
	SHAS: { name: "Sharp-tailed Sandpiper" },
	SHCO: { name: "Shiny Cowbird" },
	SHGD: { name: "Shy Ground Dove" },
	SHOS: { name: "Short-tailed Shearwater" },
	SHWR: { name: "Southern House Wren" },
	SIAC: { name: "Siberian Accentor" },
	SIRU: { name: "Siberian Rubythroat" },
	SKLA: { name: "Sky Lark" },
	SLAR: { name: "Slate-throated Redstart" },
	SLSH: { name: "San Clemente Loggerhead Shrike" },
	SMLO: { name: "Smith's Longspur" },
	SNBU: { name: "Snow Bunting" },
	SNEG: { name: "Snowy Egret" },
	SNGO: { name: "Snow Goose" },
	SNKI: { name: "Snail Kite" },
	SNOW: { name: "Snowy Owl" },
	SNPE: { name: "Snow Petrel" },
	SNPI: { name: "Scaly-naped Pigeon" },
	SNPL: { name: "Snowy Plover" },
	SNSH: { name: "Snowy Sheathbill" },
	SOAL: { name: "Sooty Albatross" },
	SOFU: { name: "Southern Fulmar" },
	SORA: { name: "Sora" },
	SOSA: { name: "Solitary Sandpiper" },
	SOSH: { name: "Sooty Shearwater" },
	SOSP: { name: "Song Sparrow" },
	SOTE: { name: "Sooty Tern" },
	SOVI: { name: "Solitary Vireo" },
	SPDO: { name: "Spotted Dove" },
	SPEI: { name: "Spectacled Eider" },
	SPGR: { name: "Spruce Grouse" },
	SPOO: { name: "Spotted-breasted Oriole" },
	SPOS: { name: "Spoonbill Sandpiper" },
	SPOW: { name: "Spotted Owl" },
	SPPI: { name: "Sprague's Pipit" },
	SPSA: { name: "Spotted Sandpiper" },
	SPSK: { name: "South Polar Skua" },
	SPTO: { name: "Spotted Towhee" },
	SRGH: { name: "Snow x Ross's Goose Hybrid" },
	SSHA: { name: "Sharp-shinned Hawk" },
	SSSP: { name: "San Clemente Sage Sparrow" },
	STAL: { name: "Short-tailed Albatross" },
	STEI: { name: "Steller's Eider" },
	STFL: { name: "Scissor-tailed Flycatcher" },
	STGR: { name: "Sharp-tailed Grouse" },
	STHA: { name: "Short-tailed Hawk" },
	STJA: { name: "Steller's Jay" },
	STKI: { name: "Swallow-tailed Kite" },
	STOF: { name: "Stolid Flycatcher" },
	STPE: { name: "Stejneger's Petrel" },
	STRO: { name: "Streak-backed Oriole" },
	STRS: { name: "Streaked Shearwater" },
	STSA: { name: "Stilt Sandpiper" },
	STSP: { name: "Sharp-tailed Sparrow" },
	STSW: { name: "Short-tailed Swift" },
	STTL: { name: "Streamertail" },
	STWO: { name: "Strickland's Woodpecker" },
	SURF: { name: "Surfbird" },
	SUSC: { name: "Surf Scoter" },
	SUTA: { name: "Summer Tanager" },
	SUWA: { name: "Sutton's Warbler" },
	SWFL: { name: "Southwestern Willow Flycatcher" },
	SWHA: { name: "Swainson's Hawk" },
	SWSN: { name: "Swinhoe's Snipe" },
	SWSP: { name: "Swamp Sparrow" },
	SWTH: { name: "Swainson's Thrush" },
	SWWA: { name: "Swainson's Warbler" },
	TABG: { name: "Taiga Bean Goose" },
	TACR: { name: "Tamaulipas Crow" },
	TAFL: { name: "Taiga Flycatcher" },
	TAPE: { name: "Tahiti Petrel" },
	TBGO: { name: "Tundra Bean-Goose" },
	TBKI: { name: "Thick-billed Kingbird" },
	TBMU: { name: "Thick-billed Murre" },
	TBPA: { name: "Thick-billed Parrot" },
	TBPR: { name: "Thin-billed Prion" },
	TBVI: { name: "Thick-billed Vireo" },
	TEWA: { name: "Tennessee Warbler" },
	THGU: { name: "Thayer's Gull" },
	THWH: { name: "Townsend's x Hermit Warbler Hybrid" },
	TIMO: { name: "Tinian Monarch" },
	TOSH: { name: "Townsend's Shearwater" },
	TOSO: { name: "Townsend's Solitaire" },
	TOWA: { name: "Townsend's Warbler" },
	TRBL: { name: "Tricolored Blackbird" },
	TRES: { name: "Tree Swallow" },
	TRFL: { name: "Traill's Flycatcher" },
	TRHE: { name: "Tricolored Heron" },
	TRKI: { name: "Tropical Kingbird" },
	TRMO: { name: "Tropical Mockingbird" },
	TRMU: { name: "Tricolored Munia" },
	TRPA: { name: "Tropical Parula" },
	TRSP: { name: "Tristram's Storm-Petrel" },
	TRUS: { name: "Trumpeter Swan" },
	TSBL: { name: "Tawny-shouldered Blackbird" },
	TUDU: { name: "Tufted Duck" },
	TUPU: { name: "Tufted Puffin" },
	TUSW: { name: "Tundra Swan" },
	TUTI: { name: "Tufted Titmouse" },
	TUVU: { name: "Turkey Vulture" },
	TWFG: { name: "Tule White-fronted Goose" },
	UDEJ: { name: "Unidentified Dark-eyed Junco" },
	UNAC: { name: "Unidentified Accipiter" },
	UNBI: { name: "Unidentified Bird" },
	UNBL: { name: "Unidentified Blackbird" },
	UNBU: { name: "Unidentified Buteo" },
	UNCH: { name: "Unidentified Chickadee" },
	UNCR: { name: "Unidentified Crow" },
	UNDO: { name: "Unidentified Dove" },
	UNDU: { name: "Unidentified Duck" },
	UNEM: { name: "Unidentified Empidonax" },
	UNFA: { name: "Unidentified Falcon" },
	UNFI: { name: "Unidentified Finch" },
	UNFL: { name: "Unidentified Flycatcher" },
	UNGN: { name: "Unidentified Gnatcatcher" },
	UNGR: { name: "Unidentified Grouse" },
	UNGU: { name: "Unidentified Gull" },
	UNHA: { name: "Unidentified Hawk" },
	UNHU: { name: "Unidentified Hummingbird" },
	UNJY: { name: "Unidentified Jay" },
	UNNU: { name: "Unidentified Nuthatch" },
	UNOR: { name: "Unidentified Oriole" },
	UNOW: { name: "Unidentified Owl" },
	UNPI: { name: "Unidentified Pipit" },
	UNRA: { name: "Unidentified Raptor" },
	UNRE: { name: "Unknown Redpoll" },
	UNSI: { name: "Unidentified Swift" },
	UNSP: { name: "Unidentified Sparrow" },
	UNSW: { name: "Unidentified Swallow" },
	UNTA: { name: "Unidentified Tanager" },
	UNTE: { name: "Unidentified Teal" },
	UNTH: { name: "Unidentified Thrush" },
	UNTR: { name: "Unidentified Thrasher" },
	UNVI: { name: "Unidentified Vireo" },
	UNWA: { name: "Unidentified Warbler" },
	UNWO: { name: "Unidentified Woodpekcer" },
	UNWR: { name: "Unidentified Wren" },
	UPSA: { name: "Upland Sandpiper" },
	URST: { name: "Unknown Rufous-sided Towhee" },
	UYRW: { name: "Unknown Yellow-rumped Warbler" },
	VABU: { name: "Varied Bunting" },
	VASW: { name: "Vaux's Swift" },
	VATH: { name: "Varied Thrush" },
	VATI: { name: "Varied Tit" },
	VCHU: { name: "Violet-crowned Hummingbird" },
	VEER: { name: "Veery" },
	VEFL: { name: "Vermilion Flycatcher" },
	VERD: { name: "Verdin" },
	VESP: { name: "Vesper Sparrow" },
	VETR: { name: "Venezuelan Troupial" },
	VGSW: { name: "Violet-green Swallow" },
	VIPE: { name: "Victoria Penguin" },
	VIRA: { name: "Virginia Rail" },
	VIWA: { name: "Virginia's Warbler" },
	WAAL: { name: "Wandering Albatross" },
	WAHO: { name: "Wattled Honeyeater" },
	WATA: { name: "Wandering Tattler" },
	WAVA: { name: "Waved Albatross" },
	WAVI: { name: "Warbling Vireo" },
	WBNU: { name: "White-breasted Nuthatch" },
	WCGR: { name: "Western/clark's Grebe" },
	WCPE: { name: "White-chinned Petrel" },
	WCPI: { name: "White-crowned Pigeon" },
	WCSE: { name: "White-collared Seedeater" },
	WCSP: { name: "White-crowned Sparrow" },
	WCTH: { name: "White-chinned Thrush" },
	WEBL: { name: "Western Bluebird" },
	WEFL: { name: "Western Flycatcher" },
	WEGR: { name: "Western Grebe" },
	WEGU: { name: "Western Gull" },
	WEHU: { name: "White-eared Hummingbird" },
	WEKI: { name: "Western Kingbird" },
	WEME: { name: "Western Meadowlark" },
	WESA: { name: "Western Sandpiper" },
	WESJ: { name: "Western Scrub Jay" },
	WESO: { name: "Western Screech-Owl" },
	WESP: { name: "Western Spindalis" },
	WETA: { name: "Western Tanager" },
	WETH: { name: "White-eyed Thrush" },
	WEVI: { name: "White-eyed Vireo" },
	WEWA: { name: "Worm-eating Warbler" },
	WEWP: { name: "Western Wood-Pewee" },
	WFIB: { name: "White-faced Ibis" },
	WFSP: { name: "White-faced Storm-Petrel" },
	WHAU: { name: "Whiskered Auklet" },
	WHCR: { name: "Whooping Crane" },
	WHIB: { name: "White Ibis" },
	WHIM: { name: "Whimbrel" },
	WHIP: { name: "White-cheeked Pintail" },
	WHIT: { name: "Whiskered Tern" },
	WHOS: { name: "Whooper Swan" },
	WHSO: { name: "Whiskered Screech-Owl" },
	WHSP: { name: "White-throated Storm-Petrel" },
	WHSW: { name: "Whistling Swan" },
	WHTE: { name: "White Tern" },
	WHWA: { name: "White Wagtail" },
	WHWO: { name: "White-headed Woodpecker" },
	WIFL: { name: "Willow Flycatcher" },
	WILL: { name: "Willet" },
	WIPH: { name: "Wilson's Phalarope" },
	WIPL: { name: "Wilson's Plover" },
	WIPT: { name: "Willow Ptarmigan" },
	WISA: { name: "Williamson's Sapsucker" },
	WISN: { name: "Wilson's Snipe" },
	WISP: { name: "Wilson's Storm-Petrel" },
	WITU: { name: "Wild Turkey" },
	WIWA: { name: "Wilson's Warbler" },
	WIWD: { name: "West Indian Whistling-Duck" },
	WIWO: { name: "West Indian Woodpecker" },
	WIWR: { name: "Winter Wren" },
	WNCR: { name: "White-necked Crow" },
	WODU: { name: "Wood Duck" },
	WOSA: { name: "Wood Sandpiper" },
	WOSP: { name: "Worthen's Sparrow" },
	WOST: { name: "Wood Stork" },
	WOTH: { name: "Wood Thrush" },
	WOWA: { name: "Wood Warbler" },
	WPWA: { name: "Western Palm Warbler" },
	WREN: { name: "Wrentit" },
	WRSA: { name: "White-rumped Sandpiper" },
	WRSH: { name: "White-rumped Shama" },
	WRSP: { name: "Wedge-rumped Storm-Petrel" },
	WRSW: { name: "White-rumped Swiftlet" },
	WTDO: { name: "White-tipped Dove" },
	WTGD: { name: "White-throated Ground-Dove" },
	WTHA: { name: "White-tailed Hawk" },
	WTKI: { name: "White-tailed Kite" },
	WTPT: { name: "White-tailed Ptarmigain" },
	WTSH: { name: "Wedge-tailed Shearwater" },
	WTSP: { name: "White-throated Sparrow" },
	WTSW: { name: "White-throated Swift" },
	WTTR: { name: "White-tailed Tropicbird" },
	WVMY: { name: "White-vented Myna" },
	WWCR: { name: "White-winged Crossbill" },
	WWDO: { name: "White-winged Dove" },
	WWJU: { name: "White-winged Junco" },
	WWSC: { name: "White-winged Scoter" },
	WWTE: { name: "White-winged Tern" },
	XAMU: { name: "Xantus's Murrelet" },
	YBCA: { name: "Yellow-billed Cardinal" },
	YBCH: { name: "Yellow-breasted Chat" },
	YBCR: { name: "Yellow-breasted Crake" },
	YBCU: { name: "Yellow-billed Cuckoo" },
	YBEL: { name: "Yellow-bellied Elaenia" },
	YBFL: { name: "Yellow-bellied Flycatcher" },
	YBLO: { name: "Yellow-billed Loon" },
	YBMA: { name: "Yellow-billed Magpie" },
	YBSA: { name: "Yellow-bellied Sapsucker" },
	YBSE: { name: "Yellow-bellied Seedeater" },
	YCBI: { name: "Yellow-crowned Bishop" },
	YCNH: { name: "Yellow-crowned Night-Heron" },
	YEBI: { name: "Yellow Bittern" },
	YEGR: { name: "Yellow Grosbeak" },
	YEJU: { name: "Yellow-eyed Junco" },
	YERA: { name: "Yellow Rail" },
	YEWA: { name: "Yellow Warbler" },
	YFCA: { name: "Yellow-fronted Canary" },
	YFGR: { name: "Yellow-faced Grassquit" },
	YFGU: { name: "Yellow-footed Gull" },
	YGVI: { name: "Yellow-green Vireo" },
	YHBL: { name: "Yellow-headed Blackbird" },
	YNAL: { name: "Yellow-nosed Albatross" },
	YPWA: { name: "Yellow Palm Warbler" },
	YRWA: { name: "Yellow-rumped Warbler" },
	YSBL: { name: "Yellow-shouldered Blackbird" },
	YSFL: { name: "Yellow-shafted Flicker" },
	YSGR: { name: "Yellow-shouldered Grassquit" },
	YTVI: { name: "Yellow-throated Vireo" },
	YTWA: { name: "Yellow-throated Warbler" },
	ZEBD: { name: "Zebra Dove" },
	ZEND: { name: "Zenaida Dove" },
	ZSHY: { name: "Zonotrichia Sparrow Hybrid" },
	ZTHA: { name: "Zone-tailed Hawk" }

};